### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rainboy93** [L-Briand/ShadowLayout#2]
Hi there,
I am very appreciate your hard work. But when I make an example it is totally not working at all.
Can you please add some executable code for testing please?
Thanks,

**Comment by L-Briand** [comment]
Hi, Thanks
I'll do a sample project in the near future to showcase it.
Can you show me your errors ?

**Comment by L-Briand** [comment]
You'll find a sample directory inside the root project. (it's a launchable android app) It contains the two example of the Readme.md.

**Comment by rainboy93** [comment]
Thank you very much!
